item {
  id: 1
  name: 'pork'
}

item {
  id: 2
  name: 'beef'
}

item {
  id: 3
  name: 'chamoc'
}

item {
  id: 4
  name: 'chilli'
}

item {
  id: 5
  name: 'tofu'
}

item{
  id:6
  name:'vegetable'
}

item {
  id: 7
  name: 'rieu'
}
